/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mini.cafe;

import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class frame_Edit extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frame_Edit.class.getName());
    private frame_selection mainMenu;
    
    /**
     * Creates new form frame_Edit
     */
    public frame_Edit() {
        initComponents();
    }
    public frame_Edit(frame_selection mainMenu) {
        initComponents();
        this.mainMenu = mainMenu;
        loadTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnSeeAll = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        customHeaderPanel1 = new com.mycompany.UI.CustomHeaderPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(246, 235, 218));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 174, -1, -1));
        jPanel2.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 145, 296, -1));

        jLabel2.setText("Search :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 123, -1, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 145, -1, -1));

        btnSeeAll.setText("See all");
        btnSeeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeAllActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeeAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 145, -1, -1));

        jLabel3.setText("Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 174, -1, -1));
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 196, 181, -1));

        jLabel4.setText("Price");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 224, -1, -1));
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 246, 181, -1));

        jLabel5.setText("Quantity");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 274, -1, -1));
        jPanel2.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 296, 181, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 613, -1, -1));

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 613, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 330, -1, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 330, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg-menu.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 101, 750, 550));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setText("Edit Menu");

        javax.swing.GroupLayout customHeaderPanel1Layout = new javax.swing.GroupLayout(customHeaderPanel1);
        customHeaderPanel1.setLayout(customHeaderPanel1Layout);
        customHeaderPanel1Layout.setHorizontalGroup(
            customHeaderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customHeaderPanel1Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(283, 283, 283))
        );
        customHeaderPanel1Layout.setVerticalGroup(
            customHeaderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customHeaderPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.add(customHeaderPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        txtName.setEditable(true);
        txtName.setText("");
        txtPrice.setText("");
        txtQty.setText("");
        this.setVisible(false);
        mainMenu.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
         txtName.setEditable(true);
        txtName.setText("");
        txtPrice.setText("");
        txtQty.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        double price;
        int Qty;
        if(txtName.getText().isBlank() && txtPrice.getText().isBlank() && txtQty.getText().isBlank()){
            JOptionPane.showMessageDialog(null,"Please fill in the information");
            return;
        }else if(txtName.getText().matches("-?\\d+")){
            JOptionPane.showMessageDialog(null,"Name must be alphabet only");
            return;
        }
        try{
            price = Double.valueOf(txtPrice.getText());
            Qty = Integer.valueOf(txtQty.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Price and Quantity must be number");
            return;
        }
        try(Connection conn1 = DBConnection.getConnection()){
            String selectSql = "SELECT * FROM product WHERE name = ?";            
            PreparedStatement pst = conn1.prepareStatement(selectSql);
            pst.setString(1,name);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                try(Connection conn2 = DBConnection.getConnection()){
                    String updateSql = "UPDATE product SET price = ?, quantity = ? WHERE name = ?";
                    PreparedStatement updatetPst = conn2.prepareStatement(updateSql);
                    updatetPst.setDouble(1,price);
                    updatetPst.setInt(2,Qty);
                    updatetPst.setString(3,name);
                    updatetPst.executeUpdate();
                }catch(Exception e){
                    e.printStackTrace();
                }
            }else{
                try(Connection conn2 = DBConnection.getConnection()){
                    String insertSql = "INSERT INTO product(name,price,quantity) VALUES (?,?,?)";            
                    PreparedStatement insertPst = conn2.prepareStatement(insertSql);
                    insertPst.setString(1,name);
                    insertPst.setDouble(2,price);
                    insertPst.setInt(3,Qty);
                    insertPst.executeUpdate();
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        loadTable();
        txtName.setEditable(true);
        txtName.setText("");
        txtPrice.setText("");
        txtQty.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        txtName.setEditable(false);
        int selectedRow = jTable1.getSelectedRow();
        String name = jTable1.getValueAt(selectedRow, 1).toString();
        double price = Double.parseDouble(jTable1.getValueAt(selectedRow, 2).toString());
        int Qty = Integer.parseInt(jTable1.getValueAt(selectedRow, 3).toString());
        txtName.setText(name);
        txtQty.setText(String.valueOf(Qty));
        txtPrice.setText(String.valueOf(price));
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        String name = jTable1.getValueAt(selectedRow, 1).toString();
        try(Connection conn = DBConnection.getConnection()){
            String deleteSql = "DELETE FROM product WHERE name = ?";
            PreparedStatement deletetPst = conn.prepareStatement(deleteSql);
            deletetPst.setString(1,name);
            deletetPst.executeUpdate();
        }catch(Exception e){
            e.printStackTrace();
        }
        txtName.setEditable(true);
        txtName.setText("");
        txtPrice.setText("");
        txtQty.setText("");
        loadTable();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSeeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeAllActionPerformed
        // TODO add your handling code here:
        txtSearch.setText("");
        loadTable();
    }//GEN-LAST:event_btnSeeAllActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            // connect database
            Connection conn = DBConnection.getConnection();
            String sql = "SELECT id, name, price, quantity FROM product WHERE name = ?";
            // query product table
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, txtSearch.getText());
            ResultSet rs = stmt.executeQuery();
            // create new table model
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Name");
            model.addColumn("Price");
            model.addColumn("Quantity");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("name"),
                    rs.getDouble("price"),
                    rs.getInt("quantity"),});
            }
            jTable1.setModel(model);
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frame_Edit().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSeeAll;
    private com.mycompany.UI.CustomHeaderPanel customHeaderPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        try {
            // connect database
            Connection conn = DBConnection.getConnection();
            String sql = "SELECT id, name, price, quantity FROM product";
            // query product table
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            // create new table model
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Name");
            model.addColumn("Price");
            model.addColumn("Quantity");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("name"),
                    rs.getDouble("price"),
                    rs.getInt("quantity"),});
            }
            jTable1.setModel(model);
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
