/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mini.cafe;

import com.itextpdf.text.BaseColor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Element;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Phrase;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class frame_Menu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frame_Table.class.getName());
    private frame_selection mainMenu;
    private Client client;
    private Table table;
    private admin admin;

    /**
     * Creates new form frame_Table
     */
    public frame_Menu() {
        initComponents();
        loadTable();
        this.client = new Client();
    }

    public frame_Menu(frame_selection mainMenu,admin admin) {
        initComponents();
        loadTable();
        this.admin = admin;
        this.mainMenu = mainMenu;
        this.client = new Client();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void loadTable() {
        try {
            // connect database
            Connection conn = DBConnection.getConnection();
            String sql = "SELECT id, name, price, quantity FROM product";
            // query product table
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            // create new table model
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Name");
            model.addColumn("Price");
            model.addColumn("Quantity");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("name"),
                    rs.getDouble("price"),
                    rs.getInt("quantity"),});
            }
            jTable_Menu.setModel(model);
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blackground = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Menu = new javax.swing.JTable();
        btnAdd = new com.mycompany.UI.RoundButton();
        btnReset = new com.mycompany.UI.RoundButton();
        btnBill = new com.mycompany.UI.RoundButton();
        btnBacktoMenu = new com.mycompany.UI.RoundButton();
        panel_Header = new com.mycompany.UI.CustomHeaderPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Cart = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labPrice = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        blackground.setBackground(new java.awt.Color(246, 235, 218));
        blackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Test", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Menu);

        blackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, 338));

        btnAdd.setText("Add to Cart");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        blackground.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 110, 30));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        blackground.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 110, 30));

        btnBill.setText("Check Bill");
        btnBill.setToolTipText("");
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });
        blackground.add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 110, 30));

        btnBacktoMenu.setText("Back");
        btnBacktoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktoMenuActionPerformed(evt);
            }
        });
        blackground.add(btnBacktoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 110, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Menu");

        javax.swing.GroupLayout panel_HeaderLayout = new javax.swing.GroupLayout(panel_Header);
        panel_Header.setLayout(panel_HeaderLayout);
        panel_HeaderLayout.setHorizontalGroup(
            panel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_HeaderLayout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel2)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        panel_HeaderLayout.setVerticalGroup(
            panel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_HeaderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        blackground.add(panel_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 730, 80));

        jTable_Cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Price"
            }
        ));
        jScrollPane3.setViewportView(jTable_Cart);

        blackground.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 330, 340));

        jPanel1.setBackground(new java.awt.Color(245, 206, 147));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Price :");

        labPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labPrice.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(8, 8, 8)
                    .addComponent(labPrice)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(labPrice))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        blackground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg-menu.jpg"))); // NOI18N
        blackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blackground, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int selectedRow = jTable_Menu.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a menu item first.");
            return;
        }

        // Retrieve data from the table
        int id = Integer.parseInt(jTable_Menu.getValueAt(selectedRow, 0).toString());
        String name = jTable_Menu.getValueAt(selectedRow, 1).toString();
        double price = Double.parseDouble(jTable_Menu.getValueAt(selectedRow, 2).toString());
        int stock = Integer.parseInt(jTable_Menu.getValueAt(selectedRow, 3).toString());

        if (stock <= 0) {
            JOptionPane.showMessageDialog(this, name + " is out of stock.");
            return;
        }

        // Add to cart
        Food f = new Food();
        f.setName(name);
        f.setPrice((int) price);  // Ensure correct casting if double
        f.setQuantity(1);
        client.addFood(f);

        // Update Database
        try (Connection conn = DBConnection.getConnection()) {
            String updateSql = "UPDATE product SET quantity = quantity - 1 WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(updateSql);
            pst.setInt(1, id);
            pst.executeUpdate();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        loadTable();      // Reload table data
        CartTable();      // Update cart UI
        labPrice.setText(client.getTotalPrice() + "");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try (Connection conn = DBConnection.getConnection()) {

            // Restore stock back to database
            for (Food f : client.getFoods()) {
                String updateSql = "UPDATE product SET quantity = quantity + ? WHERE name = ?";
                PreparedStatement pst = conn.prepareStatement(updateSql);
                pst.setInt(1, f.getQuantity());
                pst.setString(2, f.getName());
                pst.executeUpdate();
            }

            // Clear cart memory
            client.clearFoods();

            // Refresh UI
            loadTable();
            CartTable();
            labPrice.setText("0");

            JOptionPane.showMessageDialog(this, "Cart has been reset.");

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnResetActionPerformed
    private PdfPCell headerCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
        return cell;
    }

    private PdfPCell normalCell(String text) {
        return new PdfPCell(new Phrase(text));
    }

    private PdfPCell centerCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        return cell;
    }

    private PdfPCell rightCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
        return cell;
    }

    private PdfPCell noBorderCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setBorder(PdfPCell.NO_BORDER);
        return cell;
    }

    private PdfPCell noBorderRightCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setBorder(PdfPCell.NO_BORDER);
        cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
        return cell;
    }

    private Paragraph noBorderParagraph(String t) {
        Paragraph p = new Paragraph(t);
        p.setAlignment(Element.ALIGN_LEFT);
        return p;
    }

    private void addLine(Document doc) throws DocumentException {
        doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------\n"));
    }

    private void generateBillPDF() {
        try {
            String filePath = "bill.pdf";
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();

            // ---------------- HEADER ----------------
            Font header = new Font(Font.FontFamily.HELVETICA, 22, Font.BOLD);
            Font normal = new Font(Font.FontFamily.HELVETICA, 12);
            Font bold = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD);

            Paragraph shop = new Paragraph("Mini-Cafe", header);
            shop.setAlignment(Element.ALIGN_CENTER);
            document.add(shop);

            document.add(new Paragraph("UWU 258", normal));
            document.add(new Paragraph("City Index - 02025", normal));
            document.add(new Paragraph("Tel.: +456-468-987-02\n\n", normal));

            addLine(document);

            // ---------------- STORE INFO ----------------
            PdfPTable info = new PdfPTable(3);
            info.setWidthPercentage(100);
            info.setWidths(new float[]{2, 2, 2});

            info.addCell(noBorderCell("Store: 25896"));
            info.addCell(noBorderCell("22-11-2025"));
            info.addCell(noBorderCell("12:02 PM"));
            document.add(info);

            document.add(noBorderParagraph("Server:     NY 58/8"));
            document.add(noBorderParagraph("Survey code: 0000-2555-2588-4545-69\n"));

            addLine(document);

            // ---------------- ITEM TABLE ----------------
            PdfPTable orderTable = new PdfPTable(3);
            orderTable.setWidthPercentage(100);
            orderTable.setWidths(new float[]{4, 1, 2});

            orderTable.addCell(headerCell("Name"));
            orderTable.addCell(headerCell("Qty"));
            orderTable.addCell(headerCell("Price"));

            // read from cart
            DefaultTableModel cart = (DefaultTableModel) jTable_Cart.getModel();

            double total = 0;

            for (int i = 0; i < cart.getRowCount(); i++) {
                String name = cart.getValueAt(i, 0).toString();
                int qty = Integer.parseInt(cart.getValueAt(i, 1).toString());
                double price = Double.parseDouble(cart.getValueAt(i, 2).toString());

                total += price;

                orderTable.addCell(normalCell(name));
                orderTable.addCell(centerCell(String.valueOf(qty)));
                orderTable.addCell(rightCell(String.format("$%.2f", price)));
            }

            document.add(orderTable);

            addLine(document);

            // ---------------- PRICE SUMMARY ----------------


            PdfPTable priceTable = new PdfPTable(2);
            priceTable.setWidthPercentage(100);
            priceTable.setWidths(new float[]{4, 2});

            priceTable.addCell(noBorderCell("SUB TOTAL :"));
            priceTable.addCell(noBorderRightCell(String.format("$%.2f", total)));


            document.add(priceTable);

            addLine(document);

            // ---------------- THANK YOU ----------------
            Paragraph thanks = new Paragraph("THANK YOU!\n\n", bold);
            thanks.setAlignment(Element.ALIGN_CENTER);
            document.add(thanks);


            document.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error creating PDF");
        }
    }

    private void openPDF() {
        try {
            File file = new File("bill.pdf");
            if (!Desktop.isDesktopSupported()) {
                JOptionPane.showMessageDialog(null, "Desktop is not supported on this system.");
                return;
            }

            Desktop desktop = Desktop.getDesktop();
            if (file.exists()) {
                desktop.open(file);
            } else {
                JOptionPane.showMessageDialog(null, "PDF file not found.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error opening PDF: " + e.getMessage());
        }
    }

    private void clearCartAfterBill() {
        try (Connection conn = DBConnection.getConnection()) {

            

            // Clear foods from memory
            client.clearFoods();

            // Clear JTable cart UI
            CartTable();
            
            //Calculate Total income
            admin.setTotalPrice(Integer.valueOf(labPrice.getText()));
            
            // Reset total price label
            labPrice.setText("0");

            // Reload menu table after stock restored
            loadTable();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        generateBillPDF();
        openPDF();
        clearCartAfterBill();
    }//GEN-LAST:event_btnBillActionPerformed

    private void btnBacktoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktoMenuActionPerformed
        this.setVisible(false);
        mainMenu.UpdateUI(admin);
        mainMenu.setVisible(true);
    }//GEN-LAST:event_btnBacktoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frame_Table().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blackground;
    private com.mycompany.UI.RoundButton btnAdd;
    private com.mycompany.UI.RoundButton btnBacktoMenu;
    private com.mycompany.UI.RoundButton btnBill;
    private com.mycompany.UI.RoundButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_Cart;
    private javax.swing.JTable jTable_Menu;
    private javax.swing.JLabel labPrice;
    private com.mycompany.UI.CustomHeaderPanel panel_Header;
    // End of variables declaration//GEN-END:variables
/**
     * Table Reload info automatically
     */
    private void CartTable() {
        DefaultTableModel model = (DefaultTableModel) jTable_Cart.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        for (Food menu : client.getFoods()) {

            int qty = menu.getQuantity();
            double unitPrice = menu.getPrice();
            double totalPrice = qty * unitPrice;

            model.addRow(new Object[]{
                menu.getName(),
                qty,
                totalPrice
            });
        }
    }

}
