/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mini.cafe;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frame_Table extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frame_Table.class.getName());
    private frame_selection mainMenu;
    private frame_AddMenuToTable menuPage = null;
    private List<Table> tableList = new ArrayList<>();
    private List<javax.swing.JLabel> Pricelist = new ArrayList<>();
    private List<javax.swing.JLabel> StateList = new ArrayList<>();
    private admin admin;
    /**
     * Creates new form fmTable
     */
    public frame_Table() {
        initComponents();
    }

    public frame_Table(frame_selection mainMenu,admin admin) {
        initComponents();
        this.mainMenu = mainMenu;
        this.admin = admin;
        BuiltTable();
        Pricelist = Arrays.asList(labPrice1, labPrice2, labPrice3, labPrice4, labPrice5, labPrice6, labPrice7, labPrice8);
        StateList = Arrays.asList(labState1, labState2, labState3, labState4, labState5, labState6, labState7, labState8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labState1 = new javax.swing.JLabel();
        labTable = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnAddtble1 = new javax.swing.JButton();
        btnBill1 = new javax.swing.JButton();
        labPrice1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labState2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAddtble2 = new javax.swing.JButton();
        btnBill2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        labPrice2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labState3 = new javax.swing.JLabel();
        btnAddtble3 = new javax.swing.JButton();
        btnBill3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labPrice3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labState4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnAddtble4 = new javax.swing.JButton();
        btnBill4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        labPrice4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        labState5 = new javax.swing.JLabel();
        btnAddtble5 = new javax.swing.JButton();
        btnBill5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labPrice5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        labState6 = new javax.swing.JLabel();
        btnAddtble6 = new javax.swing.JButton();
        btnBill6 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labPrice6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        labState7 = new javax.swing.JLabel();
        btnAddtble7 = new javax.swing.JButton();
        btnBill7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labPrice7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        labState8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnAddtble8 = new javax.swing.JButton();
        btnBill8 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        labPrice8 = new javax.swing.JLabel();
        panel_Header = new com.mycompany.UI.CustomHeaderPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new com.mycompany.UI.RoundButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(246, 235, 218));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 200));

        labState1.setText("Empty");

        labTable.setText("Table : 1");

        jLabel29.setText("Price :");

        btnAddtble1.setText("Add");
        btnAddtble1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtble1ActionPerformed(evt);
            }
        });

        btnBill1.setText("Check Bill");
        btnBill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBill1ActionPerformed(evt);
            }
        });

        labPrice1.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labTable)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labPrice1)))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAddtble1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBill1)
                        .addGap(6, 6, 6))
                    .addComponent(labState1))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labState1)
                .addGap(46, 46, 46)
                .addComponent(labTable)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(labPrice1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtble1)
                    .addComponent(btnBill1))
                .addGap(26, 26, 26))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 200));

        labState2.setText("Empty");

        jLabel9.setText("Table : 2");

        btnAddtble2.setText("Add");
        btnAddtble2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtble2ActionPerformed(evt);
            }
        });

        btnBill2.setText("Check Bill");
        btnBill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBill2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Price :");

        labPrice2.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labState2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labPrice2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnAddtble2)
                                .addGap(18, 18, 18)
                                .addComponent(btnBill2))
                            .addComponent(jLabel9))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labState2)
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labPrice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtble2)
                    .addComponent(btnBill2))
                .addGap(26, 26, 26))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 200));

        labState3.setText("Empty");

        btnAddtble3.setText("Add");
        btnAddtble3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtble3ActionPerformed(evt);
            }
        });

        btnBill3.setText("Check Bill");
        btnBill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBill3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Price :");

        jLabel12.setText("Table : 3");

        labPrice3.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labState3)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labPrice3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAddtble3)
                        .addGap(18, 18, 18)
                        .addComponent(btnBill3)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labState3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labPrice3))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtble3)
                    .addComponent(btnBill3))
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 200));

        labState4.setText("Empty");

        jLabel13.setText("Table : 4");

        btnAddtble4.setText("Add");
        btnAddtble4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtble4ActionPerformed(evt);
            }
        });

        btnBill4.setText("Check Bill");
        btnBill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBill4ActionPerformed(evt);
            }
        });

        jLabel14.setText("Price :");

        labPrice4.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labState4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labPrice4))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnAddtble4)
                                .addGap(18, 18, 18)
                                .addComponent(btnBill4))
                            .addComponent(jLabel13))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labState4)
                .addGap(44, 44, 44)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(labPrice4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtble4)
                    .addComponent(btnBill4))
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 200));

        labState5.setText("Empty");

        btnAddtble5.setText("Add");
        btnAddtble5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtble5ActionPerformed(evt);
            }
        });

        btnBill5.setText("Check Bill");
        btnBill5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBill5ActionPerformed(evt);
            }
        });

        jLabel15.setText("Table : 5");

        jLabel16.setText("Price :");

        labPrice5.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labState5)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labPrice5))
                    .addComponent(jLabel15)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnAddtble5)
                        .addGap(18, 18, 18)
                        .addComponent(btnBill5)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labState5)
                .addGap(52, 52, 52)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(labPrice5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtble5)
                    .addComponent(btnBill5))
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 200));

        labState6.setText("Empty");

        btnAddtble6.setText("Add");
        btnAddtble6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtble6ActionPerformed(evt);
            }
        });

        btnBill6.setText("Check Bill");
        btnBill6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBill6ActionPerformed(evt);
            }
        });

        jLabel17.setText("Table : 6");

        jLabel18.setText("Price :");

        labPrice6.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labState6)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labPrice6))
                    .addComponent(jLabel17)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnAddtble6)
                        .addGap(18, 18, 18)
                        .addComponent(btnBill6)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labState6)
                .addGap(49, 49, 49)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(labPrice6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtble6)
                    .addComponent(btnBill6))
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 200));

        labState7.setText("Empty");

        btnAddtble7.setText("Add");
        btnAddtble7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtble7ActionPerformed(evt);
            }
        });

        btnBill7.setText("Check Bill");
        btnBill7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBill7ActionPerformed(evt);
            }
        });

        jLabel19.setText("Table : 7");

        jLabel20.setText("Price :");

        labPrice7.setText("0");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labState7)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labPrice7))
                    .addComponent(jLabel19)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnAddtble7)
                        .addGap(18, 18, 18)
                        .addComponent(btnBill7)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labState7)
                .addGap(46, 46, 46)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(labPrice7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtble7)
                    .addComponent(btnBill7))
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 200));

        labState8.setText("Empty");

        jLabel21.setText("Table : 8");

        btnAddtble8.setText("Add");
        btnAddtble8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtble8ActionPerformed(evt);
            }
        });

        btnBill8.setText("Check Bill");
        btnBill8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBill8ActionPerformed(evt);
            }
        });

        jLabel22.setText("Price :");

        labPrice8.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labState8))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labPrice8))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(btnAddtble8)
                                .addGap(18, 18, 18)
                                .addComponent(btnBill8)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labState8)
                .addGap(47, 47, 47)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(labPrice8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtble8)
                    .addComponent(btnBill8))
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Table");

        javax.swing.GroupLayout panel_HeaderLayout = new javax.swing.GroupLayout(panel_Header);
        panel_Header.setLayout(panel_HeaderLayout);
        panel_HeaderLayout.setHorizontalGroup(
            panel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_HeaderLayout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(jLabel2)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        panel_HeaderLayout.setVerticalGroup(
            panel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_HeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(panel_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 900, 80));

        btnBack.setText("Back to Menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 553, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg-Table.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private String generatePDFBill(Table table, int tableNumber) {
        try {
            String fileName = "Bill_Table_" + tableNumber + ".pdf";
            Document doc = new Document();
            PdfWriter.getInstance(doc, new FileOutputStream(fileName));
            doc.open();

            // ----- TITLE -----
            Font titleFont = new Font(Font.FontFamily.COURIER, 18, Font.BOLD);
            Paragraph title = new Paragraph("RECEIPT\nMINI CAFE", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(15);
            doc.add(title);

            // ----- INFO -----
            doc.add(new Paragraph("Address: 123 Sample Road, Bangkok"));
            doc.add(new Paragraph("Tel: 012-345-6789"));
            doc.add(new Paragraph("\n----------------------------------------------------------------------------------------------------------------------------------"));

            // Date Time
            Paragraph dt = new Paragraph(
                    "DATE: " + java.time.LocalDate.now()
                    + "       TIME: " + java.time.LocalTime.now().withNano(0));
            dt.setSpacingBefore(5);
            dt.setSpacingAfter(5);
            doc.add(dt);

            doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------\n"));

            // ===== TABLE =====
            PdfPTable pdfTable = new PdfPTable(3);
            pdfTable.setWidths(new float[]{1f, 3f, 2f});
            pdfTable.setWidthPercentage(100);
            pdfTable.setSpacingBefore(10);
            pdfTable.setSpacingAfter(10);

            // Header
            pdfTable.addCell(new PdfPCell(new Phrase("Quantity")));
            pdfTable.addCell(new PdfPCell(new Phrase("Name")));
            pdfTable.addCell(new PdfPCell(new Phrase("Amount")));

            // Rows
            for (Food f : table.getFoods()) {
                pdfTable.addCell(String.valueOf(f.getQuantity()));
                pdfTable.addCell(f.getName());
                pdfTable.addCell("฿" + (f.getQuantity() * f.getPrice()));
            }

            doc.add(pdfTable);

            // TOTAL
            doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
            Paragraph total = new Paragraph(
                    "Total                              ฿" + table.getTotalPrice() + " Baht"
            );
            total.setSpacingBefore(5);
            total.setSpacingAfter(10);
            doc.add(total);

            doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
            Paragraph thank = new Paragraph("THANK YOU!",
                    new Font(Font.FontFamily.COURIER, 14, Font.BOLD));
            thank.setAlignment(Element.ALIGN_CENTER);
            doc.add(thank);

            doc.close();
            return fileName;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            return null;
        }
    }

    private void openPDF(String fileName) {
        try {
            File file = new File(fileName);

            if (!Desktop.isDesktopSupported()) {
                JOptionPane.showMessageDialog(null, "Desktop is not supported.");
                return;
            }

            Desktop desktop = Desktop.getDesktop();
            if (file.exists()) {
                desktop.open(file);
            } else {
                JOptionPane.showMessageDialog(null, "PDF file not found: " + fileName);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error opening PDF: " + e.getMessage());
        }
    }
    private void btnAddtble2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtble2ActionPerformed
        // TODO add your handling code here:
        Table TableNo = tableList.get(1);
        if (menuPage == null) {
            menuPage = new frame_AddMenuToTable(this, TableNo);
        } else {
            menuPage.setTable(TableNo);
        }
        this.setVisible(false);
        menuPage.setVisible(true);
        if (menuPage != null) {
            menuPage.UpdateUI(TableNo);
        }
        menuPage.loadTable();
    }//GEN-LAST:event_btnAddtble2ActionPerformed

    private void btnAddtble3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtble3ActionPerformed
        // TODO add your handling code here:
        Table TableNo = tableList.get(2);
        if (menuPage == null) {
            menuPage = new frame_AddMenuToTable(this, TableNo);
        } else {
            menuPage.setTable(TableNo);
        }
        this.setVisible(false);
        menuPage.setVisible(true);
        if (menuPage != null) {
            menuPage.UpdateUI(TableNo);
        }
        menuPage.loadTable();
    }//GEN-LAST:event_btnAddtble3ActionPerformed

    private void btnAddtble5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtble5ActionPerformed
        // TODO add your handling code here:
        Table TableNo = tableList.get(4);
        if (menuPage == null) {
            menuPage = new frame_AddMenuToTable(this, TableNo);
        } else {
            menuPage.setTable(TableNo);
        }
        this.setVisible(false);
        menuPage.setVisible(true);
        if (menuPage != null) {
            menuPage.UpdateUI(TableNo);
        }
        menuPage.loadTable();
    }//GEN-LAST:event_btnAddtble5ActionPerformed

    private void btnAddtble6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtble6ActionPerformed
        // TODO add your handling code here:
        Table TableNo = tableList.get(5);
        if (menuPage == null) {
            menuPage = new frame_AddMenuToTable(this, TableNo);
        } else {
            menuPage.setTable(TableNo);
        }
        this.setVisible(false);
        menuPage.setVisible(true);
        if (menuPage != null) {
            menuPage.UpdateUI(TableNo);
        }
        menuPage.loadTable();
    }//GEN-LAST:event_btnAddtble6ActionPerformed

    private void btnAddtble7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtble7ActionPerformed
        // TODO add your handling code here:
        Table TableNo = tableList.get(6);
        if (menuPage == null) {
            menuPage = new frame_AddMenuToTable(this, TableNo);
        } else {
            menuPage.setTable(TableNo);
        }
        this.setVisible(false);
        menuPage.setVisible(true);
        if (menuPage != null) {
            menuPage.UpdateUI(TableNo);
        }
        menuPage.loadTable();
    }//GEN-LAST:event_btnAddtble7ActionPerformed

    private void btnAddtble8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtble8ActionPerformed
        // TODO add your handling code here:
        Table TableNo = tableList.get(7);
        if (menuPage == null) {
            menuPage = new frame_AddMenuToTable(this, TableNo);
        } else {
            menuPage.setTable(TableNo);
        }
        this.setVisible(false);
        menuPage.setVisible(true);
        if (menuPage != null) {
            menuPage.UpdateUI(TableNo);
        }
        menuPage.loadTable();
    }//GEN-LAST:event_btnAddtble8ActionPerformed

    private void btnAddtble4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtble4ActionPerformed
        // TODO add your handling code here:
        Table TableNo = tableList.get(3);
        if (menuPage == null) {
            menuPage = new frame_AddMenuToTable(this, TableNo);
        } else {
            menuPage.setTable(TableNo);
        }
        this.setVisible(false);
        menuPage.setVisible(true);
        if (menuPage != null) {
            menuPage.UpdateUI(TableNo);
        }
        menuPage.loadTable();
    }//GEN-LAST:event_btnAddtble4ActionPerformed

    private void btnBill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBill2ActionPerformed
        int tableIndex = 1; // Table 2
        Table t = tableList.get(tableIndex);

        if (t.getFoods().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Table is empty!");
            return;
        }

        String fileName = generatePDFBill(t, tableIndex + 1);
        if (fileName != null) {
            openPDF(fileName);
        }

        // Clear table after payment
        t.clearFoods();
        admin.setTotalPrice(Integer.valueOf(Pricelist.get(tableIndex).getText()));
        Pricelist.get(tableIndex).setText("0");
        StateList.get(tableIndex).setText("Empty");

        JOptionPane.showMessageDialog(this, "Bill generated & table cleared.");
    }//GEN-LAST:event_btnBill2ActionPerformed

    private void btnBill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBill3ActionPerformed
        int tableIndex = 2; // Table 3
        Table t = tableList.get(tableIndex);

        if (t.getFoods().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Table is empty!");
            return;
        }

        String fileName = generatePDFBill(t, tableIndex + 1);
        if (fileName != null) {
            openPDF(fileName);
        }

        // Clear table after payment
        t.clearFoods();
        admin.setTotalPrice(Integer.valueOf(Pricelist.get(tableIndex).getText()));
        Pricelist.get(tableIndex).setText("0");
        StateList.get(tableIndex).setText("Empty");

        JOptionPane.showMessageDialog(this, "Bill generated & table cleared.");
    }//GEN-LAST:event_btnBill3ActionPerformed

    private void btnBill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBill4ActionPerformed
        int tableIndex = 3; // Table 4
        Table t = tableList.get(tableIndex);

        if (t.getFoods().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Table is empty!");
            return;
        }

        String fileName = generatePDFBill(t, tableIndex + 1);
        if (fileName != null) {
            openPDF(fileName);
        }

        // Clear table after payment
        t.clearFoods();
        admin.setTotalPrice(Integer.valueOf(Pricelist.get(tableIndex).getText()));
        Pricelist.get(tableIndex).setText("0");
        StateList.get(tableIndex).setText("Empty");

        JOptionPane.showMessageDialog(this, "Bill generated & table cleared.");
    }//GEN-LAST:event_btnBill4ActionPerformed

    private void btnBill5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBill5ActionPerformed
        int tableIndex = 4; // Table 5
        Table t = tableList.get(tableIndex);

        if (t.getFoods().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Table is empty!");
            return;
        }

        String fileName = generatePDFBill(t, tableIndex + 1);
        if (fileName != null) {
            openPDF(fileName);
        }

        // Clear table after payment
        t.clearFoods();
        admin.setTotalPrice(Integer.valueOf(Pricelist.get(tableIndex).getText()));
        Pricelist.get(tableIndex).setText("0");
        StateList.get(tableIndex).setText("Empty");

        JOptionPane.showMessageDialog(this, "Bill generated & table cleared.");
    }//GEN-LAST:event_btnBill5ActionPerformed

    private void btnBill6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBill6ActionPerformed
        int tableIndex = 5; // Table 6
        Table t = tableList.get(tableIndex);

        if (t.getFoods().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Table is empty!");
            return;
        }

        String fileName = generatePDFBill(t, tableIndex + 1);
        if (fileName != null) {
            openPDF(fileName);
        }

        // Clear table after payment
        t.clearFoods();
        admin.setTotalPrice(Integer.valueOf(Pricelist.get(tableIndex).getText()));
        Pricelist.get(tableIndex).setText("0");
        StateList.get(tableIndex).setText("Empty");

        JOptionPane.showMessageDialog(this, "Bill generated & table cleared.");
    }//GEN-LAST:event_btnBill6ActionPerformed

    private void btnBill7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBill7ActionPerformed
        int tableIndex = 6; // Table 7
        Table t = tableList.get(tableIndex);

        if (t.getFoods().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Table is empty!");
            return;
        }

        String fileName = generatePDFBill(t, tableIndex + 1);
        if (fileName != null) {
            openPDF(fileName);
        }

        // Clear table after payment
        t.clearFoods();
        admin.setTotalPrice(Integer.valueOf(Pricelist.get(tableIndex).getText()));
        Pricelist.get(tableIndex).setText("0");
        StateList.get(tableIndex).setText("Empty");

        JOptionPane.showMessageDialog(this, "Bill generated & table cleared.");
    }//GEN-LAST:event_btnBill7ActionPerformed

    private void btnBill8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBill8ActionPerformed
        int tableIndex = 7; // Table 8
        Table t = tableList.get(tableIndex);

        if (t.getFoods().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Table is empty!");
            return;
        }

        String fileName = generatePDFBill(t, tableIndex + 1);
        if (fileName != null) {
            openPDF(fileName);
        }

        // Clear table after payment
        t.clearFoods();
        admin.setTotalPrice(Integer.valueOf(Pricelist.get(tableIndex).getText()));
        Pricelist.get(tableIndex).setText("0");
        StateList.get(tableIndex).setText("Empty");

        JOptionPane.showMessageDialog(this, "Bill generated & table cleared.");
    }//GEN-LAST:event_btnBill8ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        mainMenu.UpdateUI(admin);
        mainMenu.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBill1ActionPerformed
        int tableIndex = 0; // Table 1
        Table t = tableList.get(tableIndex);

        if (t.getFoods().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Table is empty!");
            return;
        }

        String fileName = generatePDFBill(t, tableIndex + 1);
        if (fileName != null) {
            openPDF(fileName);
        }

        // Clear table after payment
        t.clearFoods();
        admin.setTotalPrice(Integer.valueOf(Pricelist.get(tableIndex).getText()));
        Pricelist.get(tableIndex).setText("0");
        StateList.get(tableIndex).setText("Empty");

        JOptionPane.showMessageDialog(this, "Bill generated & table cleared.");
    }//GEN-LAST:event_btnBill1ActionPerformed

    private void btnAddtble1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtble1ActionPerformed
        // TODO add your handling code here:
        Table TableNo = tableList.get(0);
        if (menuPage == null) {
            menuPage = new frame_AddMenuToTable(this, TableNo);
        } else {
            menuPage.setTable(TableNo);
        }
        this.setVisible(false);
        menuPage.setVisible(true);
        if (menuPage != null) {
            menuPage.UpdateUI(TableNo);
        }
        menuPage.loadTable();
    }//GEN-LAST:event_btnAddtble1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frame_Table().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtble1;
    private javax.swing.JButton btnAddtble2;
    private javax.swing.JButton btnAddtble3;
    private javax.swing.JButton btnAddtble4;
    private javax.swing.JButton btnAddtble5;
    private javax.swing.JButton btnAddtble6;
    private javax.swing.JButton btnAddtble7;
    private javax.swing.JButton btnAddtble8;
    private com.mycompany.UI.RoundButton btnBack;
    private javax.swing.JButton btnBill1;
    private javax.swing.JButton btnBill2;
    private javax.swing.JButton btnBill3;
    private javax.swing.JButton btnBill4;
    private javax.swing.JButton btnBill5;
    private javax.swing.JButton btnBill6;
    private javax.swing.JButton btnBill7;
    private javax.swing.JButton btnBill8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labPrice1;
    private javax.swing.JLabel labPrice2;
    private javax.swing.JLabel labPrice3;
    private javax.swing.JLabel labPrice4;
    private javax.swing.JLabel labPrice5;
    private javax.swing.JLabel labPrice6;
    private javax.swing.JLabel labPrice7;
    private javax.swing.JLabel labPrice8;
    private javax.swing.JLabel labState1;
    private javax.swing.JLabel labState2;
    private javax.swing.JLabel labState3;
    private javax.swing.JLabel labState4;
    private javax.swing.JLabel labState5;
    private javax.swing.JLabel labState6;
    private javax.swing.JLabel labState7;
    private javax.swing.JLabel labState8;
    private javax.swing.JLabel labTable;
    private com.mycompany.UI.CustomHeaderPanel panel_Header;
    // End of variables declaration//GEN-END:variables

    private void BuiltTable() {
        for (int i = 0; i < 8; i++) {
            Table table = new Table();
            tableList.add(table);
        }
    }

    public void UpdateUI() {
        for (int i = 0; i < 8; i++) {
            Table table = tableList.get(i);
            javax.swing.JLabel lisprice = Pricelist.get(i);
            javax.swing.JLabel lisstate = StateList.get(i);
            lisstate.setText(table.getState());
            lisprice.setText(String.valueOf(table.getTotalPrice()));
        }
    }
}
